### PR TITLE
Debugging workflow

### PR DESCRIPTION
**Pull request by dzid26**
- build ELF
- debug in vscode (ctrl+b or F5)
- copy main.hex to root

### CODE REVIEW

**Comment by emmebrusa** [comment]
I was publishing the new version and saw your pull request.
They are not tools that I use, but if you think they can be useful, no problem integrating them.
The only exception are the changes to motor.c, in the new version I found that a few lines of code more or less can change the response of the motor, it is necessary to repeat the efficiency tests.
I will, but it won't be anytime soon.

**Comment by emmebrusa** [comment]
I think it's better to release the new version, so you can verify if the proposed changes need to be updated.

**Comment by emmebrusa** [comment]
Build elf. What is this commit for? Is it really necessary?
Requires the installation of msys64 or at least some missing dlls.
What about 32-bit systems?

It also gives me an error during build:
File_not_found

**Comment by dzid26** [comment]
Building elf that contain symbol names is what allows debugging or plotting live signals.  

The issue is with the objcopy that is used to convert elf to hex (for flashing).  I am not sure why the binary that I included doesn't work for you but works in the [CI](https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/actions/runs/9633894620/job/26568848433).  Maybe different binaries can be found that just works.

**Comment by dzid26** [comment]
I added `cp.cmd` file for Windows.  Does this work now for you?  

Does `objcopy.exe` need a dll as you mentioned?

**Comment by emmebrusa** [comment]
Same problem: "cannot find file".
Only the error number changes, instead of "make: *** [main] Error 2" it is now "make: *** [main] Error 1".

**Comment by dzid26** [comment]
This was so annoying to test.....   But I think it should work now.  On 32bit and 64bit.

**Comment by emmebrusa** [comment]
Yes, it works on Win10 64bit.

**Comment by emmebrusa** [comment]
One question, why did you copy main.exe to the main folder?

**Comment by dzid26** [comment]
main.hex copying to the root is mainly for the convenience.  

I am not sure if others will benefit, but I often save the binary with a meaningful name. Searching for it everytime in the bin folder was cumbersome. 

I then often wirelessly transfer the hex file to android phone and flash it, as described now in the second bullet here https://github.com/emmebrusa/TSDZ2-Smart-EBike-1#flashing-the-firmware-manually.

**Pull request merged**
