### PR TITLE
Building script improvements 

### PR DESCRIPTION
**Pull request by dzid26**
- Quick Readme installation instruction for confused newcomers
- Improved ini list behavior in the java configurator
- Cleaning, compiling, flashing - all done by calling makefile
- EEPROM not cleared by default
- Use /bin output directory for the build
- stm8-flash tool exe provided for Windows
- linux/windows makefiles unified
- [data_empty.ihx](https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/compare/master...dzid26:TSDZ2-Smart-EBike:building#diff-9385d98c148cfda884453b298354e66d62dfc6d42edbdb9707dcc8e733ce3c27) (empty) using actual Intel Hex format
- added github actions CI and a badge :) image

### CODE REVIEW

**Comment by emmebrusa** [comment]
Hello dzid26, I finally found the time to try your modification proposals.
Flashing with stm8flash.exe does not work, I have this error:

Press any key to flash ... (Ctl + C to stop)
stm8flash -c stlinkv2 -p stm8s105? 6 -w ../../bin/main.ihx
Determine FLASH area
libusb: error [init_device] device '\\. \ USB # VID_145F & PID_01D3 & MI_01 # 7 & 617E18A & 0 & 0001' is no longer connected!
Due to its file extension (or lack thereof), "../../bin/main.ihx" is considered as INTEL HEX format!
30957 bytes at 0x8000 ... Tries exceeded
make: *** [flash] Error 127
Flashing error !!

Isn't it better to use STVP_CmdLine.exe with Windows and stm8flash.exe with Linux only?

**Comment by dzid26** [comment]
```libusb: error [init_device] device '\. \ USB # VID_145F & PID_01D3 & MI_01 # 7 & 617E18A & 0 & 0001' is no longer connected!```
Did the USB get disconnected somehow?  I am on Windows and stm8flash.exe works completely fine for me - every time. 

Maybe the difference comes from the programmer? I can't find your vid/pid. https://devicehunt.com/view/type/usb/vendor/145F/device/01D3  

Mine this cheap one https://devicehunt.com/view/type/usb/vendor/0483/device/3748  
image
[updated](https://blog.csdn.net/weixin_42108484/article/details/81272123) with ST-LINK Utility.

**Comment by IArchi** [comment]
Hello,

Confirmed to be working on MacOS.
I run ```make``` to build the ihx file.
Then ```make flash``` to deploy on the TSDZ2 through ST-Link.

Everything went fluently.

**Comment by emmebrusa** [comment]
Hi dzid26, I really enjoyed your work, and merged it, however for flashing with windows I decided to use STVP_CmdLine.exe.
I have two STlink-V2 clones like the ones in the photo, with STVP_CmdLine they both work, with stm8flash they don't.
Regardless of the cause, I don't want to cause discomfort to others as well.
Can you check if everything is ok? Thank you.

**Comment by dzid26** [comment]
I tested it today. 
- I had STVP program installed in default path, so the flashing went fine. 
- New Walk Mode algo seems to work fine

I see that the Setting list in the Java Configurator still doesn't work great. I am fixing it now.

**Pull request merged**
