### PR TITLE
Compile and flash automatically from Linux and Mac OS

### PR DESCRIPTION
**Pull request by IArchi**
- A new shell script is available to compile and flash from a Linux or Mac OS.
- Script is automatically called from the GUI basing on the detected OS.
- Users can now backup the firmware to eventually rollback changes.

### CODE REVIEW

**Comment by dzid26** [comment]
There are some errors with the OS detection:
`OSType` should be removed. 
`Mac` should be `MacOS`.


```
OSType os = getOperatingSystem();
                                    switch(os) {
                                        case Windows:
                                            process = Runtime.getRuntime().exec("cmd /c start compile_and_flash_20 " + backup_name);
                                            break;
                                        case MacOS:
                                        case Linux:
                                            process = Runtime.getRuntime().exec("compile_and_flash_20.sh " + backup_name);
                                            break;
                                        case Other:
                                        default:
                                            JOptionPane.showMessageDialog(null, " Unknown OS.\n Please run:\ncd src/controller && make && make clear_eeprom && make flash\nto compile and flash your TSDZ2.");
                                            break;
                                    }
```

It would be good to update jar file too. Here is jar and netbeans project files.
[Java_Configurator_Source.zip](https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/files/10116430/Java_Configurator_Source.zip) Maybe you could add NetBeans project files to git? I found it in some older TSDZ2 fork. I haven't checked which files are sufficient to open the project.

**Comment by IArchi** [comment]
I've fixed my code. I've pushed the wrong version earlier.
Now, on Linux and MacOS devices, it opens a terminal like on Windows.

Regarding EEPROM, if I'm not wrong, you are already doing the samething with that Windows command:
```STVP_CmdLine -BoardName=ST-LINK -ProgMode=SWIM -Port=USB -Device=STM8S105x6 -FileProg=main.ihx -FileData=data_empty.ihx -verbose -no_loop -verif -no_warn_protect```
Especially this parameter: `-FileData=data_empty.ihx`

On Linux and MacOS, the clear_eeprom command uses the same file:
```stm8flash -c stlinkv2 -p stm8s105?6 -w data_empty.ihx```

**Comment by dzid26** [comment]
> Regarding EEPROM, if I'm not wrong, you are already doing the samething with that Windows command: `STVP_CmdLine -BoardName=ST-LINK -ProgMode=SWIM -Port=USB -Device=STM8S105x6 -FileProg=main.ihx -FileData=data_empty.ihx -verbose -no_loop -verif -no_warn_protect` Especially this parameter: `-FileData=data_empty.ihx`
This line was added by @emmebrusa when he was merging, due to some USB [issue](https://github.com/emmebrusa/TSDZ2-Smart-EBike-1/pull/33#issuecomment-1327354526).  Initially, in my PR changes, I was not clearing the EEPROM. 

I think it's going to be up to him whether to clear it or not.

**Comment by emmebrusa** [comment]
> * Script is automatically called from the GUI basing on the detected OS.

I tried the proposed changes in Ubuntu 22.04, clicking Compile&Flash in configurator, it creates ini and config.h files, but compile_and_flash_20.sh doesn't start (Allow executing file as program is enabled).
I state that I know little about Linux, what could be the problem?

**Pull request merged**
